# Generated by Django 5.1.5 on 2025-01-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_image',
            name='images',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
