# Generated by Django 5.1.5 on 2025-01-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_t_image_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_post',
            name='image_id',
        ),
        migrations.AddField(
            model_name='t_post',
            name='images',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
