# Generated by Django 5.1.5 on 2025-01-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_t_post_image_id_t_post_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_post',
            name='images',
        ),
    ]
