# Generated by Django 5.1.5 on 2025-01-22 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_t_post_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='m_Comment',
            new_name='t_Comment',
        ),
        migrations.AlterField(
            model_name='t_post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
