# Generated by Django 5.1.5 on 2025-01-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_m_comment_t_comment_alter_t_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_image',
            name='images',
            field=models.ImageField(default='', upload_to='post/images/'),
        ),
    ]
