# Generated by Django 5.1.5 on 2025-01-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_m_user_created_at_alter_m_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
