# Generated by Django 5.1.5 on 2025-01-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_m_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
